import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import Footer from "@/compnents/footer";
import { CartProvider } from '@/context/CartContext'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <CartProvider>
        {children}
        <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
